# Form implementation generated from reading ui file 'FormConsultarPedido.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1066, 753)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btnConsultarPedido = QtWidgets.QPushButton(parent=Form)
        self.btnConsultarPedido.setMinimumSize(QtCore.QSize(150, 46))
        self.btnConsultarPedido.setObjectName("btnConsultarPedido")
        self.horizontalLayout.addWidget(self.btnConsultarPedido)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Telefone:"))
        self.btnConsultarPedido.setText(_translate("Form", "Consultar Pedido"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Pizza"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Observação"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Rua"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Bairro"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Númeno"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Status"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "ValorTotal"))

#Faça o back-end dessa tela, conectando ao banco de dados para consultar o pedido
# Camada de apresentação
        self.btnConsultarPedido.clicked.connect(self.btnConsultarPedido_click)

    def btnConsultarPedido_click(self):
        pedido = PedidoBean()
        pedido.telefone = self.lineEdit.text()

        negocioPedido = Negocio_Pedido()
        dados = negocioPedido.consultarPedidos(pedido)

        if dados is not None:
            self.tableWidget.setRowCount(len(dados))

            for i in range(len(dados)):
                for j in range(9):
                    self.tableWidget.setItem(i,j, QtWidgets.QTableWidgetItem(str(dados[i][j])))
# Camada de negócio
    def consultarPedidos(self, p: PedidoBean):
        dadosPedido = Dados_Pedido()
        return dadosPedido.selectPedidos(p)
# Camada de dados
    def selectPedidos(self, p: PedidoBean):
        try:
            if os.path.isfile(self.dbfile):
                banco = sqlite3.connect("pizzaria.db")
                cursor = banco.cursor()
                cursor.execute('''
                    SELECT * FROM pedido WHERE telefone = (?)
                ''', (p.telefone, ))
                dados = cursor.fetchall()
                return dados
            else:
                return None
        except sqlite3.Error as erro:
            print(erro)
            return None
#Conecte ao botão de Consultar Pedido dentro da nossa Aplicação
        self.btnConsultarPedido.clicked.connect(self.btnConsultarPedido_click)

    def btnConsultarPedido_click(self):
        dialog = QtWidgets.QDialog()
        ui = ConsultarPedido()
        ui.setupUi(dialog)
        dialog.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())